SELECT CONCAT(E.FIRST_NAME,' ', E.LAST_NAME) AS 'Nome completo',
J.JOB_TITLE AS Cargo,
H.START_DATE AS 'Data de início do cargo',
D.DEPARTMENT_NAME AS 'Departamento'
FROM hr.employees AS E, hr.jobs AS J, hr.departments AS D, hr.job_history AS H
WHERE (H.JOB_ID = J.JOB_ID) AND (H.DEPARTMENT_ID = D.DEPARTMENT_ID) AND (H.EMPLOYEE_ID = E.EMPLOYEE_ID)
ORDER BY CONCAT(E.FIRST_NAME,' ', E.LAST_NAME) DESC, J.JOB_TITLE ASC;
