USE hr;
DELIMITER $$

DROP FUNCTION IF EXISTS
ExibirQuantidadePessoasContratadasPorMesEAno;

CREATE FUNCTION ExibirQuantidadePessoasContratadasPorMesEAno(mes INT, ano INT)
RETURNS INT READS SQL DATA
BEGIN
DECLARE total_hired INT;
    SELECT COUNT(HIRE_DATE) FROM hr.employees
    WHERE MONTH(HIRE_DATE) = mes AND YEAR(HIRE_DATE) = ano INTO total_hired;
    RETURN total_hired;
END $$

DELIMITER ;

SELECT EXIBIRQUANTIDADEPESSOASCONTRATADASPORMESEANO(6, 1987);
