SELECT * FROM hr.jobs;
SELECT JOB_TITLE AS 'Cargo', MAX_SALARY AS 'Nível',
CASE 
WHEN MAX_SALARY BETWEEN 5000 AND 10001 THEN 'Baixo'
WHEN MAX_SALARY BETWEEN 10001 AND 20001 THEN 'Médio'
WHEN MAX_SALARY BETWEEN 20001 AND 30001 THEN 'Alto'
ELSE 'Altíssimo'
END
FROM hr.jobs
ORDER BY JOB_TITLE;

