SELECT UCASE(CONCAT(E.FIRST_NAME,' ', E.LAST_NAME)) AS 'Nome completo',
H.START_DATE AS 'Data de início',
E.SALARY AS 'Salário'
FROM hr.employees AS E, hr.jobs AS J, hr.job_history AS H
WHERE (H.JOB_ID = J.JOB_ID) AND (E.EMPLOYEE_ID = H.EMPLOYEE_ID) AND MONTH(H.START_DATE)IN ('1','2','3')
ORDER BY CONCAT(E.FIRST_NAME,' ', E.LAST_NAME) ASC, H.START_DATE ASC;
