SELECT A.JOB_TITLE AS 'Cargo',ROUND(AVG(B.SALARY), 2) AS 'Média salarial',
CASE
WHEN ROUND(AVG(B.SALARY), 2) BETWEEN 2000 AND 5801 THEN 'Júnior'
WHEN ROUND(AVG(B.SALARY), 2) BETWEEN 5801 AND 7501 THEN 'Pleno'
WHEN ROUND(AVG(B.SALARY), 2) BETWEEN 7501 AND 10501 THEN 'Sênior'
ELSE 'CEO'
END AS 'Senioridade'
FROM hr.employees AS B 
INNER JOIN hr.jobs AS A
WHERE	 B.JOB_ID = A.JOB_ID
GROUP BY JOB_TITLE
ORDER BY ROUND(AVG(B.SALARY), 2);
